# Generated by Django 6.0.3 on 2026-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.URLField(blank=True),
        ),
    ]
