# Generated by Django 6.0.3 on 2026-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.URLField(),
        ),
    ]
